apiVersion: v1
kind: ConfigMap
metadata:
  name: fis-process-config
data:
  DB_URL: jdbc:postgresql://postgres:5432/fis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  FIS_SECURITY_ENABLED: "true"
  SERVER_SSL_ENABLED: "true"
  RABBITMQ_SSL_ENABLED: "true"
  REDIS_SSL_ENABLED: "true"
